name: Deploy AdNexus

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            echo "SSH Connected Successfully"
            whoami
            hostname
            set -e

            echo "===== AdNexus Deployment Started ====="

            # Agar folder nahi hai ya git repository nahi hai
            if [ ! -d "/var/www/AdNexus/.git" ]; then
              echo "===== Cloning Repository ====="
              rm -rf /var/www/AdNexus
              git clone https://github.com/amansahajanand-beep/AdNexus.git AdNexus
            fi

            cd /var/www/AdNexus

            echo "===== Fetching Latest Code ====="
            git fetch origin master

            echo "===== Updating to Latest Master ====="
            git reset --hard origin/master

            echo "===== Latest Commit ====="
            git log -1 --oneline

            echo "===== Installing Frontend Dependencies ====="
            cd frontend
            npm install

            echo "===== Building Frontend ====="
            npm run build

            echo "===== Installing Backend Dependencies ====="
            cd ../backend
            npm install

            echo "===== Restarting Backend ====="
            pm2 restart AdNexus

            echo "===== Saving PM2 ====="
            pm2 save

            echo "===== Deployment Completed ====="
